### ISSUE TITLE
Hello, how to get the pre-training weights ("last_SFSNiD.pth") in step2？

### ISSUE THREAD

**Issue by chener311** [Xiaofeng-life/SFSNiD#4]

**Comment by chener311** [comment]
Thanks for the answer. In addition, the picture became blurry after training, do you have such a situation?

**Comment by Xiaofeng-life** [comment]
> Thanks for the answer. In addition, the picture became blurry after training, do you have such a situation?

The results (pictures) obtained by the supervised training process should be with blurry details. Which dataset set you are using?

**Comment by chener311** [comment]
I used the NightHaze dataset, and both the semi-supervised training and the final result were blurrier than the original hazy image.

**Comment by Xiaofeng-life** [comment]
> I used the NightHaze dataset, and both the semi-supervised training and the final result were blurrier than the original hazy image.

NightHaze dataset do not need semi-supervised traning. The supervised process is designed for it. The semi-supervised process is used for real-world images.

**Comment by Xiaofeng-life** [comment]
sloved
