### ISSUE TITLE
Code for Realistic Brightness Loss 

### ISSUE THREAD

**Issue by JZhu1208** [Xiaofeng-life/SFSNiD#7]
Thank you very much for your excellent work. I did not find the code for Realistic Brightness Loss (Sec.3.4) in your public repository. I would be grateful if you could tell me where the code is or publish it.

**Comment by Xiaofeng-life** [comment]
> Thank you very much for your excellent work. I did not find the code for Realistic Brightness Loss (Sec.3.4) in your public repository. I would be grateful if you could tell me where the code is or publish it.

The training code for Realistic Brightness Loss (Sec.3.4) is provided in the folder "task_SFSNiD/train_SFSNiD_semi_supervised.py"
