### ISSUE TITLE
Yes, I am a bit confused about this. I have noticed that some dehazing tasks use the original size to test PSNR, and the PSNR value of the original size is slightly lower than that of 256 × 256.

### ISSUE THREAD

**Issue by yushanwendiepisode** [Xiaofeng-life/SFSNiD#8]
Thank you for your reply. As far as I know, it is traditional operations to train model by resizing the training images, and then use its checkpoint to test images with whole size.  Why are psnr so different when I just change the size of the test images? As you say, I can train from scratch and make the training and test images of the same size, but it's inflexible when training multiple datasets with different input sizes. Besides, for a fair comparison, both the training and the test set in SFSNiD are resized to 256. And are the other comparison methods treated in the same way? I would appreciate it if you could help me out.

_Originally posted by @jm-xiong in https://github.com/Xiaofeng-life/SFSNiD/issues/6#issuecomment-2187773651_

**Comment by Xiaofeng-life** [comment]
The reason is that some algorithms cannot accept real-world images of arbitrary sizes as input. In our paper, real-world evaluation is an important part. So we set all algorithms to have the same output size. Perhaps you can resize the output instead of using the experimental results provided in my paper.

**Comment by yushanwendiepisode** [comment]
> 是的，我观察到了同样的问题。对于不同尺寸的测试图像，评估结果可能略有不同。我们将所有算法设置为具有相同的输出大小。原因是某些算法无法接受任意大小的真实世界图像作为输入。在我们的论文中，真实世界的评估是一个重要的部分。也许您可以调整输出的大小，而不是使用我的论文中提供的实验结果。

Thank you for your answer. I have another confusion. Did you use 5000 images for each of the NHCL, NHCM, and NHCD datasets? (Excluding 500 bright images from each dataset and using low light images as GT), or only using 500 low light and 500 foggy PNG images, I noticed that other images are in BMP format and some have high contrast and brightness.

**Comment by yushanwendiepisode** [comment]
> Yes, I have observed the same problem. The evaluation results may be slightly different for test images of different sizes. We set all algorithms to have the same output size. The reason is that some algorithms cannot accept real-world images of arbitrary sizes as input. In our paper, real-world evaluation is an important part. Perhaps you can resize the output instead of using the experimental results provided in my paper.

Thank you for your answer. I have another confusion. Did you use 5000 images for each of the NHCL, NHCM, and NHCD datasets? (Excluding 500 bright images from each dataset and using low light images as GT), or only using 500 low light and 500 foggy PNG images, I noticed that other images are in BMP format and some have high contrast and brightness.
